name: tweet
description: A sample command-line application.
version: 0.0.4

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  actions_toolkit_dart: ^0.5.1
  twitter_api_v2: ^4.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
